# Generated by Django 3.2.8 on 2023-11-23 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phonemarket', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phones',
            options={'ordering': ['id']},
        ),
    ]
